language: python

build_image: vauxoo/odoo-80-image-shippable-auto

python:
  - "2.7"

env:
  - VERSION="7.0" ODOO_REPO="odoo/odoo" INCLUDE="oml"  #  Change "oml_all" to "oml" because test is too long and travis is aborting
  # - VERSION="7.0" ODOO_REPO="odoo/odoo" UNIT_TEST="1"  # Comment because is too too long

virtualenv:
  system_site_packages: true

install:
  - git clone https://github.com/vauxoo/maintainer-quality-tools.git -b master ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly
  - ${TRAVIS_BUILD_DIR}/travis/travis_install_mx_nightly ${VERSION}
  - git clone --single-branch --depth=1 https://github.com/Vauxoo/addons-vauxoo.git -b ${VERSION} ${HOME}/addons-vauxoo

script:
  - travis_run_tests

after_success:
  coveralls
